version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=development
      # Database
      - POSTGRES_PRISMA_URL=${POSTGRES_PRISMA_URL}
      - POSTGRES_URL_NON_POOLING=${POSTGRES_URL_NON_POOLING}
      - PGHOST=${PGHOST}
      - PGHOST_UNPOOLED=${PGHOST_UNPOOLED}
      - PGUSER=${PGUSER}
      - PGDATABASE=${PGDATABASE}
      - PGPASSWORD=${PGPASSWORD}
      - POSTGRES_URL=${POSTGRES_URL}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}
      - POSTGRES_URL_NO_SSL=${POSTGRES_URL_NO_SSL}
      # Authentication
      - NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
      - CLERK_SECRET_KEY=${CLERK_SECRET_KEY}
      - NEXT_PUBLIC_CLERK_SIGN_IN_URL=/sign-in
      - NEXT_PUBLIC_CLERK_SIGN_UP_URL=/sign-up
      # AI
      - GOOGLE_GEMINI_API_KEY=${GOOGLE_GEMINI_API_KEY}
      # Storage
      - BLOB_READ_WRITE_TOKEN=${BLOB_READ_WRITE_TOKEN}
      # Payments
      - NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=${NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
      - NEXT_PUBLIC_STRIPE_PRICE_ID_PRO_MONTHLY=${NEXT_PUBLIC_STRIPE_PRICE_ID_PRO_MONTHLY}
      - NEXT_PUBLIC_STRIPE_PRICE_ID_PRO_PLUS_MONTHLY=${NEXT_PUBLIC_STRIPE_PRICE_ID_PRO_PLUS_MONTHLY}
      # Base URL
      - NEXT_PUBLIC_BASE_URL=${NEXT_PUBLIC_BASE_URL:-http://localhost:3000}
    volumes:
      - /src/node_modules        
      - /src/.next                
    develop:
      watch:
        - path: ./package.json
          action: rebuild 
        - path: ./next.config.ts
          action: rebuild
        - path: ./package-lock.json
          action: rebuild
        - path: .
          target: /src
          action: sync
          ignore:
            - node_modules/
            - .next/

